fnc_user: fnc
fnc_project_root: "{{ playbook_dir | dirname }}"
fnc_compose_file: "{{ fnc_project_root }}/deploy/compose.yaml"
fnc_data_dir: "{{ fnc_project_root }}/data"
fnc_config_dir: "{{ fnc_project_root }}/config"
fnc_default_config_src: "{{ fnc_project_root }}/config/config.json"

netprobe_ap_conn_name: fnc-ap
netprobe_ap_ifname: wlan0
netprobe_ap_ssid_prefix: FNC
netprobe_ap_psk: FNC-demo-2026
netprobe_ap_address: 192.168.50.1/24
netprobe_ap_band: bg
