fnc_invoking_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id, true) }}"
fnc_source_root: "{{ playbook_dir | dirname }}"
fnc_runtime_root: /opt/field-network-checker
fnc_source_app_dir: "{{ fnc_source_root }}/app"
fnc_source_compose_file: "{{ fnc_source_root }}/deploy/compose.yaml"
fnc_source_default_config_src: "{{ fnc_source_root }}/config/config.json"
fnc_data_dir: "{{ fnc_runtime_root }}/data"
fnc_config_dir: "{{ fnc_runtime_root }}/config"

netprobe_ap_conn_name: fnc-ap
netprobe_ap_ifname: wlan0
netprobe_ap_ssid_prefix: FNC
netprobe_ap_psk: FNC-demo-2026
netprobe_ap_address: 192.168.50.1/24
netprobe_ap_band: bg
