- name: Build Field Network Checker locally
  hosts: local
  roles:
    - role: base
      tags: base
      become: true
    - role: docker
      tags: docker
      become: true
    - role: network_ap
      tags: network_ap
      become: true
    - role: app
      tags: app
