- name: Build Field Network Checker locally
  hosts: local
  become: true
  roles:
    - role: base
      tags: base
    - role: docker
      tags: docker
    - role: network_ap
      tags: network_ap
    - role: app
      tags: app
